#    _  __ _  _    _         
#   | |/ /(_)| |_ | |_  _  _ 
#   | ' < | ||  _||  _|| || |
#   |_|\_\|_| \__| \__| \_, |
#                       |__/ 
layout tall
#
# ======================================================
# Импорт файлов
# ======================================================
include                     themes/catppuccin/mocha.conf
#
# ======================================================
# Настройки терминала
# ======================================================
#
# Шрифт
#
font_family                 FiraCode Nerd Font
font_size                   14.0
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
#
# Прозрачность
#
background_opacity          0.75
dynamic_background_opacity  1
hide_window_decorations     yes
selection_foreground        none
selection_background        none
#
# Прокрутка
#
scrollback_lines            2000
wheel_scroll_min_lines      1
#
# Курсор
#
cursor_blink_interval       0.75
cursor_stop_blinking_after  1
#
# Остальное
#
confirm_os_window_close     0
window_padding_width        16
enable_audio_bell           no
#
# ======================================================
# Горячие клавиши для терминала
# ======================================================
#
# Увеличить размер шрифта
#
map ctrl+plus               change_font_size all +1
map ctrl+equal              change_font_size all +1
map ctrl+kp_add             change_font_size all +1
#
# Уменьшить размер шрифта
#
map ctrl+minus              change_font_size all -1
map ctrl+underscore         change_font_size all -1
map ctrl+kp_subtract        change_font_size all -1
#
# Сбросить размер шрифта
#
map ctrl+0                  change_font_size all 0
map ctrl+kp_0               change_font_size all 0
